schema_generation:
    datapath: "BIRD/bird_dataset"
    num_of_entries: 192
    model_name: "claude"
    prompt_type: "cot"
    method: "text"
    base_data_path: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/SQUiD/dataset"
    logs_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/logs/schema"
    results_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage1"

value_identification:
    datapath: "BIRD/bird_dataset/text_cot_claude"
    num_of_entries: 192
    model_name: "claude"
    method: "symbolic"
    base_data_path: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage1"
    logs_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/logs/values"
    results_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage2"
    schema_path: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage1/BIRD/bird_dataset/text_cot_claude.json"

value_population:
    datapath: "BIRD/bird_dataset/text_cot_claude"
    num_of_entries: 192
    model_name: "claude"
    method: "TS"
    base_data_path: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage2symbolic"
    logs_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/logs/population"
    results_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage3"
    symbolic_path: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage2symbolic/BIRD/bird_dataset/text_cot_claude.json"

database_generation:
    datapath: "BIRD/bird_dataset/text_cot_claude"
    num_of_entries: 192
    model_name: "claude"
    method: "TS"
    base_data_path: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/stage3"
    logs_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/logs/database"
    results_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/"

baseline:
    datapath: "BIRD/bird_dataset"
    num_of_entries: 192
    model_name: "claude"
    method: None
    base_data_path: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/SQUiD/dataset"
    logs_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/logs/baseline"
    results_dir: "/Users/blkcoder/Desktop/SQUiD Project/CSCI-6040---Final-Project---SQUiD-Reproduction/results/reproduction/baseline"